[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  pre_cmd = [ "templ generate" ]
  include_ext = ["go", "tpl", "templ"]
  exclude_file = ["*_templ.go"]
  exclude_dir = ["vendor", "node_modules", "tmp"]
  silent = false
